all: Q1 Q2 Q3 Q4 Q5 Q6

Q1: Q1.c
	gcc Q1.c -o Q1

Q2: Q2.c 
	gcc Q2.c -o Q2

Q3: Q3.c 
	gcc Q3.c -o Q3 

Q4: Q4.c 
	gcc Q4.c -o Q4

Q5: Q5.c
	gcc Q5.c -o Q5

Q6: Q6.c
	gcc Q6.c -o Q6

clean:
	rm -rf Q1 Q2 Q3 Q4 Q5 Q6